-- Expand demo catalog with comprehensive coverage
INSERT INTO catalog_items (
  external_id, platform, title, description, price, currency, size, condition,
  item_url, image_url, attributes
) VALUES 
-- More Hoodies & Sweatshirts
(
  'demo-black-zip-hoodie-1',
  'depop',
  'Black Zip-Up Hoodie - Oversized',
  'Cozy oversized zip-up hoodie in black with kangaroo pocket. Perfect athleisure piece.',
  38.00,
  'EUR',
  'L',
  'Good',
  'https://www.depop.com/products/demo-black-zip-hoodie-1',
  'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400',
  '{"itemType": "hoodie", "category": "zip hoodie", "fabricType": "cotton blend", "primaryColors": ["black"], "silhouette": "oversized", "length": "standard", "aesthetic": ["athleisure", "streetwear"], "notableDetails": ["zip closure", "oversized", "kangaroo pocket"], "closureType": "zipper", "era": "modern"}'::jsonb
),
(
  'demo-grey-crop-sweat-1',
  'vinted',
  'Cropped Grey Sweatshirt',
  'Trendy cropped sweatshirt in heather grey. Perfect for layering.',
  32.00,
  'EUR',
  'M',
  'Excellent',
  'https://www.vinted.com/items/demo-grey-crop-sweat-1',
  'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
  '{"itemType": "sweatshirt", "category": "cropped sweatshirt", "fabricType": "cotton", "primaryColors": ["grey"], "silhouette": "cropped", "length": "cropped", "aesthetic": ["casual", "trendy"], "notableDetails": ["cropped hem", "crew neck"], "era": "modern"}'::jsonb
),
(
  'demo-beige-hoodie-1',
  'tise',
  'Beige Oversized Hoodie',
  'Cozy oversized hoodie in neutral beige tone.',
  44.00,
  'EUR',
  'L',
  'Good',
  'https://www.tise.com/items/demo-beige-hoodie-1',
  'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=400',
  '{"itemType": "hoodie", "category": "pullover hoodie", "fabricType": "cotton blend", "primaryColors": ["beige"], "silhouette": "oversized", "aesthetic": ["cozy", "minimalist"], "notableDetails": ["oversized", "hooded", "drawstring"], "era": "modern"}'::jsonb
),
-- Heels & Boots
(
  'demo-black-stiletto-1',
  'depop',
  'Black Pointed Stiletto Heels',
  'Classic black stiletto heels with pointed toe. Timeless elegance.',
  65.00,
  'EUR',
  '38',
  'Excellent',
  'https://www.depop.com/products/demo-black-stiletto-1',
  'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400',
  '{"itemType": "heels", "category": "stiletto heels", "fabricType": "synthetic leather", "primaryColors": ["black"], "aesthetic": ["elegant", "classic"], "notableDetails": ["pointed toe", "stiletto heel", "high heel"], "heelHeight": "high", "era": "modern"}'::jsonb
),
(
  'demo-nude-heels-1',
  'vinted',
  'Nude Beige Pumps',
  'Versatile nude beige pumps with block heel.',
  58.00,
  'EUR',
  '39',
  'Good',
  'https://www.vinted.com/items/demo-nude-heels-1',
  'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=400',
  '{"itemType": "heels", "category": "pumps", "fabricType": "leather", "primaryColors": ["nude", "beige"], "aesthetic": ["versatile", "classic"], "notableDetails": ["block heel", "round toe"], "heelHeight": "medium", "era": "modern"}'::jsonb
),
(
  'demo-ankle-boots-1',
  'depop',
  'Black Leather Ankle Boots',
  'Edgy black leather ankle boots with chunky sole.',
  89.00,
  'EUR',
  '38',
  'Excellent',
  'https://www.depop.com/products/demo-ankle-boots-1',
  'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=400',
  '{"itemType": "boots", "category": "ankle boots", "fabricType": "leather", "primaryColors": ["black"], "aesthetic": ["edgy", "streetwear"], "notableDetails": ["chunky sole", "ankle height", "lace-up"], "era": "modern"}'::jsonb
),
(
  'demo-studded-boots-1',
  'tise',
  'Studded Combat Boots',
  'Black combat boots with silver studded details.',
  92.00,
  'EUR',
  '37',
  'Good',
  'https://www.tise.com/items/demo-studded-boots-1',
  'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=400',
  '{"itemType": "boots", "category": "combat boots", "fabricType": "leather", "primaryColors": ["black"], "aesthetic": ["edgy", "punk"], "notableDetails": ["studded details", "combat style", "platform sole"], "era": "modern"}'::jsonb
),
-- Tops
(
  'demo-white-tee-1',
  'vinted',
  'Classic White Oversized T-Shirt',
  'Minimalist oversized white tee. Wardrobe essential.',
  18.00,
  'EUR',
  'L',
  'Good',
  'https://www.vinted.com/items/demo-white-tee-1',
  'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
  '{"itemType": "top", "category": "t-shirt", "fabricType": "cotton", "primaryColors": ["white"], "silhouette": "oversized", "aesthetic": ["minimalist", "casual"], "notableDetails": ["oversized", "crew neck"], "era": "modern"}'::jsonb
),
(
  'demo-black-crop-top-1',
  'depop',
  'Black Ribbed Crop Top',
  'Trendy ribbed crop top in black with long sleeves.',
  26.00,
  'EUR',
  'S',
  'Excellent',
  'https://www.depop.com/products/demo-black-crop-top-1',
  'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=400',
  '{"itemType": "top", "category": "crop top", "fabricType": "ribbed knit", "primaryColors": ["black"], "silhouette": "fitted", "length": "cropped", "aesthetic": ["trendy", "Y2K"], "notableDetails": ["ribbed texture", "cropped", "long sleeves"], "era": "modern"}'::jsonb
),
(
  'demo-silk-cami-1',
  'vinted',
  'Champagne Silk Camisole',
  'Luxurious silk cami in champagne color with lace trim.',
  42.00,
  'EUR',
  'M',
  'Excellent',
  'https://www.vinted.com/items/demo-silk-cami-1',
  'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400',
  '{"itemType": "top", "category": "camisole", "fabricType": "silk", "primaryColors": ["champagne", "beige"], "aesthetic": ["elegant", "minimalist"], "notableDetails": ["lace trim", "silk fabric", "adjustable straps"], "era": "modern"}'::jsonb
),
(
  'demo-striped-tee-1',
  'tise',
  'Breton Stripe Long Sleeve Top',
  'Classic navy and white striped long sleeve tee.',
  28.00,
  'EUR',
  'M',
  'Good',
  'https://www.tise.com/items/demo-striped-tee-1',
  'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400',
  '{"itemType": "top", "category": "striped top", "fabricType": "cotton", "primaryColors": ["navy", "white"], "pattern": "striped", "aesthetic": ["classic", "casual"], "notableDetails": ["breton stripes", "long sleeves"], "era": "modern"}'::jsonb
),
-- Accessories & Socks
(
  'demo-lace-ankle-socks-1',
  'depop',
  'White Lace Trim Ankle Socks',
  'Delicate ankle socks with romantic lace trim detail.',
  12.00,
  'EUR',
  'One Size',
  'New',
  'https://www.depop.com/products/demo-lace-ankle-socks-1',
  'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=400',
  '{"itemType": "socks", "category": "ankle socks", "fabricType": "cotton blend", "primaryColors": ["white"], "aesthetic": ["feminine", "romantic"], "notableDetails": ["lace trim", "ankle length"], "era": "modern"}'::jsonb
),
(
  'demo-black-lace-socks-1',
  'vinted',
  'Black Sheer Lace Socks',
  'Elegant sheer socks with intricate lace pattern.',
  14.00,
  'EUR',
  'One Size',
  'New',
  'https://www.vinted.com/items/demo-black-lace-socks-1',
  'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=400',
  '{"itemType": "socks", "category": "lace socks", "fabricType": "nylon", "primaryColors": ["black"], "aesthetic": ["elegant", "feminine"], "notableDetails": ["lace pattern", "sheer", "ankle length"], "era": "modern"}'::jsonb
),
(
  'demo-leather-bag-1',
  'depop',
  'Cognac Leather Crossbody Bag',
  'Vintage-style cognac leather crossbody with brass hardware.',
  76.00,
  'EUR',
  'One Size',
  'Good',
  'https://www.depop.com/products/demo-leather-bag-1',
  'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400',
  '{"itemType": "bag", "category": "crossbody bag", "fabricType": "leather", "primaryColors": ["brown", "cognac"], "aesthetic": ["vintage", "classic"], "notableDetails": ["brass hardware", "adjustable strap", "leather"], "era": "vintage"}'::jsonb
),
-- Jackets & Outerwear
(
  'demo-denim-jacket-1',
  'vinted',
  'Vintage Light Wash Denim Jacket',
  'Classic 90s denim jacket in light blue wash.',
  55.00,
  'EUR',
  'M',
  'Good',
  'https://www.vinted.com/items/demo-denim-jacket-1',
  'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400',
  '{"itemType": "jacket", "category": "denim jacket", "fabricType": "denim", "primaryColors": ["light blue"], "aesthetic": ["vintage", "casual"], "notableDetails": ["90s style", "light wash", "button closure"], "era": "90s"}'::jsonb
),
(
  'demo-leather-jacket-1',
  'depop',
  'Black Leather Biker Jacket',
  'Edgy black leather jacket with asymmetric zipper.',
  145.00,
  'EUR',
  'S',
  'Excellent',
  'https://www.depop.com/products/demo-leather-jacket-1',
  'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400',
  '{"itemType": "jacket", "category": "leather jacket", "fabricType": "leather", "primaryColors": ["black"], "aesthetic": ["edgy", "rock"], "notableDetails": ["biker style", "asymmetric zipper", "belt"], "era": "modern"}'::jsonb
),
(
  'demo-blazer-1',
  'tise',
  'Oversized Beige Linen Blazer',
  'Relaxed oversized blazer in natural linen.',
  68.00,
  'EUR',
  'L',
  'Excellent',
  'https://www.tise.com/items/demo-blazer-1',
  'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400',
  '{"itemType": "jacket", "category": "blazer", "fabricType": "linen", "primaryColors": ["beige"], "silhouette": "oversized", "aesthetic": ["minimalist", "professional"], "notableDetails": ["oversized", "linen", "notched lapel"], "era": "modern"}'::jsonb
),
-- Dresses
(
  'demo-slip-dress-1',
  'vinted',
  'Sage Green Satin Slip Dress',
  'Elegant satin slip dress in trendy sage green.',
  58.00,
  'EUR',
  'M',
  'Excellent',
  'https://www.vinted.com/items/demo-slip-dress-1',
  'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400',
  '{"itemType": "dress", "category": "slip dress", "fabricType": "satin", "primaryColors": ["green", "sage"], "silhouette": "slip", "length": "midi", "aesthetic": ["elegant", "minimalist"], "notableDetails": ["satin fabric", "adjustable straps", "cowl neck"], "era": "modern"}'::jsonb
),
(
  'demo-maxi-dress-1',
  'depop',
  'Floral Boho Maxi Dress',
  'Flowy bohemian maxi dress with floral print.',
  62.00,
  'EUR',
  'S',
  'Good',
  'https://www.depop.com/products/demo-maxi-dress-1',
  'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400',
  '{"itemType": "dress", "category": "maxi dress", "fabricType": "cotton", "primaryColors": ["multicolor"], "pattern": "floral", "length": "maxi", "aesthetic": ["bohemian", "romantic"], "notableDetails": ["floral print", "flowy", "v-neck"], "era": "modern"}'::jsonb
),
(
  'demo-mini-dress-1',
  'tise',
  'Black Mini Dress with Cutouts',
  'Trendy black mini dress with strategic cutout details.',
  48.00,
  'EUR',
  'XS',
  'Excellent',
  'https://www.tise.com/items/demo-mini-dress-1',
  'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400',
  '{"itemType": "dress", "category": "mini dress", "fabricType": "jersey", "primaryColors": ["black"], "length": "mini", "aesthetic": ["trendy", "edgy"], "notableDetails": ["cutout details", "bodycon", "mini length"], "era": "modern"}'::jsonb
),
-- More Pants
(
  'demo-cargo-pants-1',
  'vinted',
  'Olive Green Cargo Pants',
  'Y2K style cargo pants with multiple pockets.',
  46.00,
  'EUR',
  '30',
  'Good',
  'https://www.vinted.com/items/demo-cargo-pants-1',
  'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400',
  '{"itemType": "pants", "category": "cargo pants", "fabricType": "cotton twill", "primaryColors": ["olive", "green"], "aesthetic": ["Y2K", "streetwear"], "notableDetails": ["cargo pockets", "relaxed fit", "drawstring"], "era": "Y2K"}'::jsonb
),
(
  'demo-leather-pants-1',
  'depop',
  'Black Faux Leather Straight Leg Pants',
  'Sleek faux leather pants with straight leg cut.',
  72.00,
  'EUR',
  'M',
  'Excellent',
  'https://www.depop.com/products/demo-leather-pants-1',
  'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=400',
  '{"itemType": "pants", "category": "leather pants", "fabricType": "faux leather", "primaryColors": ["black"], "silhouette": "straight", "aesthetic": ["edgy", "modern"], "notableDetails": ["faux leather", "straight leg", "high waisted"], "era": "modern"}'::jsonb
),
-- Trendy Items
(
  'demo-mesh-top-1',
  'depop',
  'Black Mesh Long Sleeve Top',
  'Layering mesh top with sheer fabric.',
  24.00,
  'EUR',
  'M',
  'Good',
  'https://www.depop.com/products/demo-mesh-top-1',
  'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400',
  '{"itemType": "top", "category": "mesh top", "fabricType": "mesh", "primaryColors": ["black"], "aesthetic": ["Y2K", "trendy"], "notableDetails": ["sheer fabric", "mesh", "layering piece"], "era": "modern"}'::jsonb
),
(
  'demo-corset-top-1',
  'vinted',
  'White Corset Top',
  'Structured corset top with boning detail.',
  52.00,
  'EUR',
  'S',
  'Excellent',
  'https://www.vinted.com/items/demo-corset-top-1',
  'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=400',
  '{"itemType": "top", "category": "corset", "fabricType": "cotton blend", "primaryColors": ["white"], "aesthetic": ["romantic", "trendy"], "notableDetails": ["boning", "structured", "hook closure"], "era": "modern"}'::jsonb
),
(
  'demo-oversized-shirt-1',
  'tise',
  'White Oversized Button-Up Shirt',
  'Minimalist oversized white shirt. Perfect layering piece.',
  34.00,
  'EUR',
  'L',
  'Good',
  'https://www.tise.com/items/demo-oversized-shirt-1',
  'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400',
  '{"itemType": "shirt", "category": "button-up", "fabricType": "cotton", "primaryColors": ["white"], "silhouette": "oversized", "aesthetic": ["minimalist", "versatile"], "notableDetails": ["oversized", "button closure", "collared"], "era": "modern"}'::jsonb
)