// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gerwikyaggikykftcyxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdlcndpa3lhZ2dpa3lrZnRjeXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTEzNDEsImV4cCI6MjA3NDcyNzM0MX0.I_-b2YdhX9vK0cmKRwMVAPw69Up7PZFi8hHkBkUeWZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});